- name: Deploy disabled module
  shell: '/opt/wildfly/bin/jboss-cli.sh --connect --controller=172.17.0.1:9990 --user={{ demo.user }} --password={{ demo.password }} --commands="deploy /home/dmitry/Desktop/modules/hello-world-project-for-docker-1.0-SNAPSHOT.ear  --name=hello-world-project-for-docker-1.0-SNAPSHOT.ear --disabled"'
#  args:
#    chdir: "{{ vars[role_name].installdir }}"